### PR TITLE
Security upgrades for Django, Pillow and ecdsa

### PR DESCRIPTION
**Pull request by vikoivun**
Upgrade these to clear the requirements.io alert. Thus the alert will again become useful for detecting any new problems.

### CODE REVIEW

**Comment by vikoivun** [comment]
Pillow upgrade has potential to break things.

**Comment by vikoivun** [comment]
> I wasn't able to find any `PIL` imports from the code base so the Pillow dependency is probably used only indirectly through Django. It was added on commit [a341eab](https://github.com/City-of-Helsinki/tunnistamo/commit/a341eab558fc782f923bfee345af203ebdaedac6), which also added an `ImageField`. If this is the only use for it, it should be relatively easy to verify that it still works, e.g. by adding a new Service object with an image from Django Admin and verifying it works correctly.

Indeed. However it looks like we've never even used that functionality. Thus the verifying part is a wee bit tricky. At least I'm still able to upload a file and get the link back from the API

**Comment by suutari-ai** [comment]
> Indeed. However it looks like we've never even used that functionality. Thus the verifying part is a wee bit tricky. At least I'm still able to upload a file and get the link back from the API

The `ImageField` should check that the uploaded content is actually an image. Try uploading garbage to it and it should detect it (raise ValidationError). If that works, then Pillow is doing its job there.

**Comment by vikoivun** [comment]
> > Indeed. However it looks like we've never even used that functionality. Thus the verifying part is a wee bit tricky. At least I'm still able to upload a file and get the link back from the API
> 
> The `ImageField` should check that the uploaded content is actually an image. Try uploading garbage to it and it should detect it (raise ValidationError). If that works, then Pillow is doing its job there.

Thanks for the tip! Uploading a garbage image indeed failed. So Pillow is doing its basic work.

**Pull request merged**
